### ISSUE TITLE
Write git status(es) into .livesync_mutex

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/livesync#3]
It would be helpful to see the current development status on the remote machine to explain its current behavior. The output of `git status` per synchronized folder should be a good start.

### Task list

- [x] write git summary to mutex file
- [x] handle missing git
- [x] add commit hash
- [x] @rodja review

**Comment by falkoschindler** [comment]
Implemented in https://github.com/zauberzeug/livesync/commit/b8f62994e29972d60ad8b81c7628814e9d27422f.

The git information needs to be passed into the mutex `set` and `is_free` methods, but it works. To avoid issues with quotes when echoing the multiline string into the mutex file, they are replaced with single quotes.

**Comment by falkoschindler** [comment]
Random thoughts:

- Now livesync depends on git being installed. We might want to make this optional.
- `git status` does not show the commit hash. Maybe there's a better representation of the current status.

**Comment by rodja** [comment]
We could simply add the shortend hash above the git status call: https://stackoverflow.com/a/7617078/364388

**Comment by falkoschindler** [comment]
I updated the git summary accordingly: https://github.com/zauberzeug/livesync/commit/6f9757cc5ce6350bf272b5d32e083c17dcb41708.
Now the mutex file looks like this:

```
Falkos-MBP 2022-09-02T07:59:38.620688

/Users/falko/Projects/livesync --> ~/livesync
[f3dddb0]
## main...origin/main
 M livesync/livesync.py
```
